basic.sh.in:improve test accuracy
Some of tests from this script were passing when they shouldn't have.

diff --git a/test/COMMON b/test/COMMON
--- a/test/COMMON
+++ b/test/COMMON
@@ -22,6 +22,18 @@ test_result_want_fail() {
   set -x
 }
 
+test_result_want_true() {
+  set +x
+  if [ $1 = 0 ]; then
+    echo "\n  --:Test failure:--"
+    exit 1
+  fi
+
+  echo "  -:Test passed:-"
+  set -x
+}
+
+
 #
 # HOME is defined in test/Makefile as "tmp-home". But...
 # Don't use the var $HOME here, just in case something went wrong somewhere ;)
